project:
  type: website
  output-dir: docs

website:
  title: "Preston R. Johnston"
  navbar:
    right:
      - href: index.qmd
        text: about
  search: false
  favicon: MIT_logo.jpeg
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

